// <auto-generated />
using System;
using Intern_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intern_Project.Migrations
{
    [DbContext(typeof(Intern_ProjectDbContext))]
    [Migration("20250723084927_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Intern_Project.Models.Bildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EsikMiktar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParcaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("Intern_Project.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("Intern_Project.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Intern_Project.Models.Parca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Parcalar");
                });

            modelBuilder.Entity("Intern_Project.Models.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiparisDurumu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("Intern_Project.Models.SiparisUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiparisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisUrunler");
                });

            modelBuilder.Entity("Intern_Project.Models.StokYonetimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EsikMiktar")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParcaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stoklar");
                });

            modelBuilder.Entity("Intern_Project.Models.Parca", b =>
                {
                    b.HasOne("Intern_Project.Models.Kategori", "Kategori")
                        .WithMany("Parcalar")
                        .HasForeignKey("KategoriId");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Intern_Project.Models.SiparisUrun", b =>
                {
                    b.HasOne("Intern_Project.Models.Siparis", "Siparis")
                        .WithMany("Urunler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("Intern_Project.Models.Kategori", b =>
                {
                    b.Navigation("Parcalar");
                });

            modelBuilder.Entity("Intern_Project.Models.Siparis", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
